// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// TODO: Add your Android Firebase Options here from Console
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '', // AIzaSyBb0Nte...
    appId: '', // 1:90708996366:android:2ebdd...
    messagingSenderId: '', // 90708996..
    projectId: '', // project
    storageBucket: '', // project.firebasestorage.app
  );

  /// TODO: Add your iOS Firebase Options here from Console
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '', // AIzaSyB1UCtoCo5WovYWmo70EDzUj...
    appId: '', // 1:90708996366:ios:58ee5d3f6fa7f...
    messagingSenderId: '', // 907089...
    projectId: '', // project
    storageBucket: '', // project.firebasestorage.app
    iosBundleId: '', // com.project.app
  );

// TODO: add google-services.json file to android > app
// TODO: add GoogleService-info.plist file to ios > Runner
}
